# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ch < Formula
  desc "Docker config and shell manager for using (or misusing) containers as dev environments"
  homepage "https://github.com/camerondurham/ch"
  version "0.3.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.7/ch-darwin-amd64.zip"
      sha256 "27e68a2ec772300e7f40d21e5a4e2b4d5d5df3e468d20ef775e9ec70412e58a8"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.7/ch-darwin-arm64.zip"
      sha256 "c5204f422cb9eecfb6af514feaa44e383fc60d3d063d98858daf7352710a14cf"

      def install
        bin.install "ch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.7/ch-linux-arm64.zip"
      sha256 "3e06282e1ab1b47700ab79f9c795d034a2c82dfcc8d63da1d466643c33af603c"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.7/ch-linux-amd64.zip"
      sha256 "3aa4f4cb50813216deed81c23f55af02c2c27ad71a2629bdbed5a9a26b254014"

      def install
        bin.install "ch"
      end
    end
  end

  test do
    system "#{bin}/ch --version"
  end
end
