# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ch < Formula
  desc "Docker config and shell manager for using (or misusing) containers as dev environments"
  homepage "https://github.com/camerondurham/ch"
  version "0.3.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch-darwin-arm64.zip"
      sha256 "2d4a759d7f2c4011bc949061d14a19ae8859d0e7e35542c84792fdd4aa0ca7a4"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch-darwin-amd64.zip"
      sha256 "ed0bbc39ce3d5d575c9483dc53a9066cc9d28ab6d05abee5b022391c95a3455e"

      def install
        bin.install "ch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch-linux-arm64.zip"
      sha256 "a18c43ec7e75e3e6e5566aa852794cbb85f6c1a1934b77136cf07a0bb6523ef7"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch-linux-amd64.zip"
      sha256 "145840889a11c578fabe85f88bfd3f0e40757eb5835b07c1faa1364d63cc1f51"

      def install
        bin.install "ch"
      end
    end
  end

  test do
    system "#{bin}/ch --version"
  end
end
