# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ch < Formula
  desc "Docker config and shell manager for using (or misusing) containers as dev environments"
  homepage "https://github.com/camerondurham/ch"
  version "0.3.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch_0.3.6_darwin_amd64.tar.gz"
      sha256 "32896729427ed8137169bb182a7ab3b7604a8240095b6858fb2506e46a1c83ea"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch_0.3.6_darwin_arm64.tar.gz"
      sha256 "315943eae429b1d4c6facb5c01d2131dc041344b4304e6a1df6bdbde6e9b690b"

      def install
        bin.install "ch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch_0.3.6_linux_arm64.tar.gz"
      sha256 "b05c8e6e9dbd98f7ce935bb525d62e1c179b32d53f1b39ce61a6273e6b8f3920"

      def install
        bin.install "ch"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/camerondurham/ch/releases/download/v0.3.6/ch_0.3.6_linux_amd64.tar.gz"
      sha256 "cb32d73b852aa352cadc19f06549f4f382b4dbd78558a3bddc386f293575591a"

      def install
        bin.install "ch"
      end
    end
  end

  test do
    system "#{bin}/ch --version"
  end
end
